import { useState } from 'react';
import { createStoredImage, isValidImageFile, type StoredImage } from '../../lib/imageStorage';
import { cardStorage } from '../../lib/cardStorage';
import type { DraftCard, Character } from '../../types/card';
import OCRResults from './OCRResults';
import SavedCardsGallery from './SavedCardsGallery';
import './upload.css';

export default function UploadPage() {
  const [uploadedImage, setUploadedImage] = useState<StoredImage | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [approvedCards, setApprovedCards] = useState<DraftCard[] | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];

    if (!file) {
      return;
    }

    // Validate the file is an image
    if (!isValidImageFile(file)) {
      setError('Please select a valid image file (PNG, JPG, GIF, or WebP)');
      return;
    }

    try {
      setError(null);
      const storedImage = await createStoredImage(file);
      setUploadedImage(storedImage);
    } catch (err) {
      setError('Failed to read the image file. Please try again.');
      console.error('Image read error:', err);
    }
  };

  const handleClear = () => {
    setUploadedImage(null);
    setError(null);
    setApprovedCards(null);
    setSaveSuccess(false);
  };

  const handleCardsApproved = (cards: DraftCard[]) => {
    setApprovedCards(cards);
    setSaveSuccess(false);
  };

  const handleSaveCards = async () => {
    if (!approvedCards || approvedCards.length === 0) {
      setError('No cards to save');
      return;
    }

    setIsSaving(true);
    setError(null);

    try {
      // Convert DraftCard to Character and save to storage
      const charactersToSave: Character[] = approvedCards.map((draftCard) => ({
        id: '', // Will be generated by cardStorage.add()
        faceId: draftCard.faceId,
        face: draftCard.face,
        name: draftCard.matchedName || 'Unknown',
        traits: draftCard.traits || [],
        imageUrl: draftCard.face.id, // Use face ID as reference; in real app would be cropped image
      }));

      // Save each card to storage
      await Promise.all(charactersToSave.map((card) => cardStorage.add(card)));

      setSaveSuccess(true);

      // Reset after successful save
      setTimeout(() => {
        handleClear();
      }, 2000);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to save cards';
      setError(errorMessage);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="upload-page">
      <section className="upload-section" aria-label="Image upload">
        <h2>Upload Scanned Page</h2>
        <p className="upload-subtitle">
          Select a scanned image of a Guess Who game board to get started.
        </p>

        <div className="upload-input-container">
          <label htmlFor="image-input" className="upload-label">
            Choose image file
          </label>
          <input
            id="image-input"
            type="file"
            accept="image/*"
            onChange={handleFileSelect}
            className="upload-input"
            aria-describedby="image-help"
          />
          <p id="image-help" className="upload-help-text">
            Accepted formats: PNG, JPG, GIF, WebP
          </p>
        </div>

        {error && (
          <div className="upload-error" role="alert">
            {error}
          </div>
        )}

        {uploadedImage && (
          <div className="uploaded-image-container">
            <div className="uploaded-image-info">
              <p className="uploaded-filename">
                <strong>File:</strong> {uploadedImage.filename}
              </p>
              <p className="uploaded-size">
                <strong>ID:</strong> {uploadedImage.id}
              </p>
            </div>

            <figure className="uploaded-image-figure">
              <img
                src={uploadedImage.dataUrl}
                alt="Uploaded image preview"
                className="uploaded-image"
              />
              <figcaption>Image preview - stored locally in your browser</figcaption>
            </figure>

            {approvedCards ? (
              <div className="upload-cards-approved">
                <div className="upload-cards-approved-message">
                  <h4>Cards Approved</h4>
                  <p>{approvedCards.length} card(s) ready to save.</p>
                </div>

                {error && (
                  <div className="upload-error" role="alert">
                    {error}
                  </div>
                )}

                {saveSuccess && (
                  <div className="upload-success" role="status">
                    <p>Cards saved successfully!</p>
                  </div>
                )}

                <button
                  onClick={handleSaveCards}
                  disabled={isSaving}
                  className="upload-save-cards-button"
                  aria-label="Save approved cards to storage"
                >
                  {isSaving ? 'Saving...' : 'Save Cards'}
                </button>
              </div>
            ) : (
              <OCRResults
                imageDataUrl={uploadedImage.dataUrl}
                filename={uploadedImage.filename}
                onReviewComplete={handleCardsApproved}
              />
            )}

            <button onClick={handleClear} className="clear-button">
              Clear and Upload New
            </button>
          </div>
        )}
      </section>

      <SavedCardsGallery />
    </div>
  );
}
